version: '3'

services:
  postgres:
    image: 'postgres'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  
  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/minhas-financas-api
      - app-gems:/app-gems
    environment: 
      REDIS_URL: 'redis://redis:6379/0'

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1025:25
      - 1080:80

  redis:
    image: 'redis:6.0.9-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs.sh
    volumes:
      - '.:/minhas-financas-api'
      - app-gems:/app-gems

volumes:
  redis:
  postgres:
  app-gems: